### ISSUE TITLE
Some problem about compile a kernel

### ISSUE THREAD

**Issue by qpzm1258** [Coolexe/shooteru-ics-crc-3.0.16-e733189#11]
I want to compile a kernel for htc x515d(shooerct).I Meet with some difficulties .Can you help me?
1.When I try to put a patch to the kernel from 3.0.16 to 3.0.0.I found 19 files mismatching.I want to applied linux kernel patch 3.0.16->80. What can I do?
2.I try to ignore this mismatches and update to 3.0.43.But in x515d I found every  process take up 0 RAM.Can you tell me why?

**Comment by Coolexe** [comment]
check this commit
https://github.com/Coolexe/shooteru-ics-crc-3.0.16-e733189/commit/26da7d0ad778d6f07aa5161d7cdd7cfde68c2f18
